### PR TITLE
added JDF second run; forgot before

### PR DESCRIPTION
**Pull request by xiaodaigh**
forgot to run JDF in the second run of benchmarks. So adding them now.

### CODE REVIEW

**Comment by bkamins** [comment]
Looks good. Just please re-run the notebook to make execution count start from 1 not 2.

**Comment by bkamins** [comment]
Now you have not run the several last cells I think.

**Comment by xiaodaigh** [comment]
reran all

**Comment by bkamins** [comment]
Thank you!

**Pull request merged**
