### PR TITLE
updated with JLSO and reading from ZipFile.jl

### PR DESCRIPTION
**Pull request by xiaodaigh**

### CODE REVIEW

**Review by bkamins — CHANGES_REQUESTED** [review]
Thank you for the commit. I have the following remarks for you to consider before I merge it:
1. I use `using` statements only on top of each notebook; please do not reload the already loaded packages; and the new packages that need to be loaded should be loaded on top
2. Please update Project.toml and Manifest.toml to reflect new packages (if you are not clear how to do it let me know and I will do it later)
3. The notebook must be stand-alone (runnable). Therefore in the zip-file example please either first create the file by compressing it and then decompress it (like I did with gzip) or add an example zip file to the folder.
4. When reading a zip-file please do not use bare `z.files[1]`, but also make sure that you are decompressing the file you intended (by checking its name)
5. Are you sure that JLSO.jl is exact serialization - not just a binary format to store data (at least as of now - if I remember correctly there were some issues that write-load did not preserve all types properly) - this was the reason I have not included it earlier in the tutorial (but hopefully things have changed and now work cleanly)

**Comment by xiaodaigh** [comment]
about 1. Do you think we should try to make the tutorial more skimmable? E.g. by adding using to where each example lies? I saw that CodecLib was loaded only before it was used so have this question. Otherwise, I am happy to make those changes.

**Comment by bkamins** [comment]
Actually I should move `using CodecZlib` up 😄 - thank you for pointing this. Loading libraries on top of the file is a standard approach in Julia and I would stick to it (this way user knows exactly what are dependencies of a given notebook).

But what we can do is to add information in comments which libraries are required for the specific sections.

Thank you!

**Comment by bkamins** [comment]
I have just checked and JLSO.jl works great! Then can you also please add it to performance benchmarks section?

**Review by bkamins — APPROVED** [review]
Thank you! Feel free to submit other PRs to this repo or DataFrames.jl 😄.

**Comment by bkamins** [comment]
You might want to have a look how I have updated your PR in the next commit.

**Pull request merged**
