### PR TITLE
[WIP] Portuguese tutorials

### PR DESCRIPTION
**Pull request by storopoli**
This is a Work in progress. Please do not merge!

- [x] Translate `README.md`
- [x] Translate `01_constructors.jl`
- [x] Translate ` 02_basicinfo.jl`
- [x] Translate `03_missingvalues.jl`
- [x] Translate `04_loadsave.jl`
- [x] Translate `05_columns.jl`
- [x] Translate `06_rows.jl`
- [x] Translate `07_factors.jl`
- [x] Translate `08_joins.jl`
- [x] Translate `09_reshaping.jl`
- [x] Translate `10_transforms.jl`
- [x] Translate `11_performance.jl`
- [x] Translate `12_pitfalls.jl`
- [x] Translate `13_extras.jl`

The `.ipynb` conversion to Literate `.jl` was done by @miguelraz in #30.

### CODE REVIEW

**Comment by miguelraz** [comment]
Not that there is a call to `activate` the environment that requires to also copy a `.toml` file from the repo. I missed that before you forked it

**Comment by storopoli** [comment]
@miguelraz done in storopoli/Julia-DataFrames-Tutorial@199b9ae8a92a21654090bcb906f34e2964c3ebc0.

**Comment by storopoli** [comment]
I am leaving joins as *joins* since in Portuguese we generally use the english version of the word and we rarely use the exact Portuguese translation that would be "juntar". We say "Então damos um join" which means "So we join".

**Comment by storopoli** [comment]
Ok @miguelraz and @bkamins the translation is done. It is ready to revision and then, afterwards, ready to be converted to Pluto by @miguelraz.

**Comment by miguelraz** [comment]
FWIW, join is also used in Spanish, and I mostly left those untouched (but clarifying the meaning first)

**Comment by bkamins** [comment]
@miguelraz: please let me know when this is good to merge

**Comment by ronisbr** [comment]
Hi @bkamins, @storopoli, and @miguelraz 

I read this translation and I have nothing to add. Amazing work @storopoli !!

**Comment by miguelraz** [comment]
As mentioned in the other thread, I produced the .jl files from a stale vwrsion of the repo. I'm uploading more corrections tomorrow - this is NOT ready to merge until then.

**Comment by storopoli** [comment]
Thank you @ronisbr! @miguelraz if it needs any sort of revision let me know (if you found any in the Spanish I will replicate it in the Portuguese)

**Comment by bkamins** [comment]
To avoid blocking users I have updated the Jupyter Notebooks to 1.1.1 release of DataFrames.jl. Fortunately the changes are minor:
* Notebook 4, comment under cell 6 about memory mapping
* Notebook 4, instructions for JDF.jl
* Notebook 4, exclude one JSON timing in reading plot as it is very slow
* Notebook 6, added an example of `subset`
* Notebook 7, changes in comparing of categorical vs underlying type; and change of `get` to `unwrap`

**Comment by storopoli** [comment]
Since the portuguese translation followed the spanish ones from @miguelraz I will wait for his updates and see the diffs and do the updates on the portuguese version. Does that sound OK to you guys?

**Comment by bkamins** [comment]
This is what I assumed, but I wanted to let you know about the changes.

**Pull request closed without merging**
