### PR TITLE
Typos and fixes

### PR DESCRIPTION
**Pull request by xiaodaigh**
Apologies for the frequent PRs, but I really wanted to correct some typos and apply some fixes to the graphs which had plotted the same figures for first and second bar due to coding error.

I also added some missing columns to the bigdf, so that we can test writing some columns with missing.

### CODE REVIEW

**Comment by bkamins** [comment]
No problem. However, I cannot see any changes in this PR (0 lines added, 0 lines removed).

Please make sure that you check out current master of this package from my repo and apply the changes on top of it.

**Comment by xiaodaigh** [comment]
Sorry let me look into it. I was doing this from the command line, and it looked fine then.

**Comment by xiaodaigh** [comment]
fixed

**Comment by bkamins** [comment]
Thank you

**Comment by bkamins** [comment]
Ah - I have completely missed merging this PR. Sorry for this. If it is still relevant can you please do the updates to the current master? Thank you!

**Comment by xiaodaigh** [comment]
I hate Jupternotebook and git. I need to tread thru the changes from beginning to see what's changed.

**Comment by bkamins** [comment]
I am closing this as we are switching to Literate.jl very soon. Thank you for the proposal.

**Pull request closed without merging**
